# Generated by Django 5.2.6 on 2025-09-28 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('reservation_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.reservation_flight')),
            ],
        ),
    ]
