# Generated by Django 5.2.6 on 2025-09-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_costumer_employee_manager_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('CUSTOMER', 'costumer'), ('EMPLOYEE', 'employee'), ('MANAGER', 'manager')], default='CUSTOMER', max_length=8),
        ),
    ]
