# Generated by Django 5.2.6 on 2025-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
