# Generated by Django 5.2.6 on 2025-09-28 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='create_on',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 9, 28, 15, 55, 58, 985732, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
