# Generated by Django 5.2.6 on 2025-09-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('flight', '0003_alter_flight_create_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_flight',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.reservation'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='create_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
