# Generated by Django 5.2.6 on 2025-09-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_reservation_flight_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_flight',
            name='departure_city',
            field=models.CharField(default='City', max_length=100),
        ),
    ]
