# Generated by Django 5.2.6 on 2025-09-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_reservation_flight_departure_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation_flight',
            name='departure_city',
        ),
    ]
