# Generated by Django 5.2.6 on 2025-09-30 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_remove_reservation_flight_departure_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsrout',
            name='flight',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
    ]
