# Generated by Django 5.2.6 on 2025-09-28 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateField(default=datetime.datetime(2025, 9, 28, 15, 55, 29, 994099, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCEL', 'Cancel')], default='Pending', max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
