# Generated by Django 5.2.6 on 2025-09-28 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 9, 28, 15, 55, 58, 988623, tzinfo=datetime.timezone.utc)),
        ),
    ]
