# Generated by Django 5.2.6 on 2025-10-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_reservation_nr_reservation'),
        ('payment', '0004_payment_reservation_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.reservation'),
        ),
    ]
