# Generated by Django 5.2.6 on 2025-09-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_count', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('room_view', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('room_number', models.IntegerField()),
                ('room_capacity', models.PositiveIntegerField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.roomtype')),
            ],
        ),
    ]
