# Generated by Django 5.2.6 on 2025-09-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInclusivePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FullBoardPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StandardPackges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PackageRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_package', models.CharField(choices=[(models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.allinclusivepackage'), 'All inclusive'), (models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.fullboardpackage'), 'Full board'), (models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.standardpackges'), 'Standard')], max_length=100)),
                ('ALL_INCLUSIVE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.allinclusivepackage')),
                ('FULL_BOARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.fullboardpackage')),
                ('type_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.roomtype')),
                ('STANDARD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.standardpackges')),
            ],
        ),
    ]
