# Generated by Django 5.2.6 on 2025-09-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_allinclusivepackage_fullboardpackage_standardpackges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageroom',
            name='ALL_INCLUSIVE',
        ),
        migrations.RemoveField(
            model_name='packageroom',
            name='FULL_BOARD',
        ),
        migrations.RemoveField(
            model_name='packageroom',
            name='STANDARD',
        ),
        migrations.RemoveField(
            model_name='packageroom',
            name='type_room',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(choices=[('DELUXE', 'Deluxe'), ('LUXURY', 'Luxury'), ('DOUBLE', 'Double'), ('SINGLE', 'Single')]),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('name', models.CharField(choices=[('ALL INCLUSICE', 'All inclusive'), ('FULL BOARD', 'Full board'), ('', 'Standard')], default='')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.roomtype')),
            ],
        ),
        migrations.DeleteModel(
            name='AllInclusivePackage',
        ),
        migrations.DeleteModel(
            name='FullBoardPackage',
        ),
        migrations.DeleteModel(
            name='StandardPackges',
        ),
        migrations.DeleteModel(
            name='PackageRoom',
        ),
    ]
