# Generated by Django 5.2.6 on 2025-09-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_remove_packageroom_all_inclusive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('ALL INCLUSICE', 'All inclusive'), ('FULL BOARD', 'Full board'), ('STANDARD', 'Standard')], default='STANDARD'),
        ),
    ]
