# Generated by Django 5.2.6 on 2025-09-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_benefitspackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='room_type',
        ),
    ]
