# Generated by Django 5.2.6 on 2025-09-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_remove_package_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='room_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation.roomtype'),
        ),
    ]
