# Generated by Django 5.2.6 on 2025-09-21 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_package_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefitspackage',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='benefits_package',
            field=models.ManyToManyField(to='accommodation.benefitspackage'),
        ),
        migrations.AlterField(
            model_name='package',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.roomtype'),
        ),
    ]
