# Generated by Django 5.2.6 on 2025-09-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0008_remove_benefitspackage_package_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='benefits_package',
            new_name='benefits',
        ),
    ]
