# Generated by Django 5.2.6 on 2025-09-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0009_rename_benefits_package_package_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitspackage',
            name='code',
            field=models.CharField(default='code', max_length=100),
        ),
    ]
