# Generated by Django 5.2.6 on 2025-10-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_reservation_has_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCEL', 'Cancel')], default='PENDING'),
        ),
    ]
