# Generated by Django 5.2.6 on 2025-10-03 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0010_benefitspackage_code'),
        ('bookings', '0003_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='package_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accommodation.package'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Cancel', 'Cancel')], default='Pending'),
        ),
    ]
