# Generated by Django 5.2.6 on 2025-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_reservation_package_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='nr_reservation',
            field=models.CharField(unique=True),
        ),
    ]
